### ISSUE TITLE
[UnicodeDecodeError]: error with decoding 

### ISSUE THREAD

**Issue by LSYS** [LSYS/runPyNB#2]
Error code for reference:

```
$ runpynb Untitled.ipynb -t 500000
ARGS=Namespace(notebooks=['Untitled.ipynb'], timeout=500000, sequence=False, output=False, version=None, quiet=False)

Start time: 2022-08-08 15:24:25
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\Scripts\runpynb", line 60, in <module>
    run_notebooks(
  File "D:\ProgramData\Anaconda3\lib\site-packages\runpynb\runpynb.py", line 59, in run_notebooks
    nb = nbformat.read(f, nbformat.NO_CONVERT)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nbformat\__init__.py", line 165, in read
    buf = fp.read()
  File "D:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1041: character maps to <undefined>
```

**Comment by LSYS** [comment]
`nbformat` uses `utf-8` encoding: https://github.com/jupyter/nbformat/issues/74
